# Generated by Django 2.1.5 on 2019-02-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact1',
            new_name='Contact',
        ),
    ]
