# Generated by Django 2.1.5 on 2019-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0003_contact_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('capital', models.CharField(max_length=24)),
                ('population', models.IntegerField()),
                ('sea', models.BooleanField()),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
    ]
